# Generated by Django 4.1.7 on 2023-03-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('contactno', models.BigIntegerField()),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=30)),
                ('vmodel', models.IntegerField()),
                ('vnumberplate', models.CharField(max_length=20)),
                ('rateperhour', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vtype', models.CharField(max_length=30)),
                ('vnoplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicleinfo')),
            ],
        ),
    ]
