# Generated by Django 4.1.7 on 2023-04-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registertable'),
        ),
    ]
