# Generated by Django 4.1.7 on 2023-04-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicleinfo_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='vnoplate',
            new_name='vid',
        ),
    ]
