# Generated by Django 4.1.7 on 2023-04-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookings_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='vtype',
        ),
    ]
