# Generated by Django 4.1.7 on 2023-04-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_bookings_vtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bdate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicleinfo'),
        ),
    ]
