# Generated by Django 4.1.7 on 2023-04-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bookings_bdate_alter_bookings_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
